[settings]

PLANE_WIDTH = 1000.0
PLANE_HEIGHT = 100.0
SQUISH_ROOM = 2.0
CIRCLE_DIAMETER = 90.0

SEVER_DISTANCE = 0.0
CUT_OFF_MARGIN = 40.0
CIRCLES_PER_CLEAN = 4

FIRST_CIRCLE_PRECUT_ANGLE = 90.0
CIRCLE_PRECUT_ANGLE = 35.0

ARC_STOP_ANGLE_FIRST_ROW = 90.0
WASTE_CUT_LENGTH_FIRST_ROW = 25.0

ARC_STOP_ANGLE = 135.0
WASTE_CUT_LENGTH = 15.0
ARC_OVERLAP_ANGLE = 10.0

POP_OUT_STOP_ANGLE = 30
GENERATE_POP_OUT = false

X_GAP = 0.0
Y_GAP = 2.0
Y_GAP_WINDOW = 2.0

PATTERN = "hex"
DIAMETER_OPTIONS = [80, 70, 60, 50]

FEED_RATE = 170
TRAVEL_RATE = 600

ORIGIN_X = 10.0
ORIGIN_Y = 160.0
OUTPUT_FILE = "circles.gcode"

SINGLE_WINDOW_ONLY = false

RAIL_LENGTH = 2131.646
MATERIAL_LENGTH = 1540.0
LEAVE_UNCUT = 30
Z_FEED_RATE = 200

SAFETY_BURN_OFF_X_DISTANCE = 1050.0
SAFETY_BURN_OFF_Y_DISTANCE = 50.0

CUTTING_TEMP = 10
BURN_OFF_TEMP = 26
TEMP_SET_TIME = 4
BURN_OFF_TIME = 10
COOL_DOWN_TIME = 8
COOL_DOWN_TIME_FROM_CUT_TEMP = 4

LEFT_CLEAN_REPEATS = 0
RIGHT_CLEAN_REPEATS = 0

Y_AXIS_MAX_LIMIT = 280.0
USE_HARDWARE_HOMING = false
